name: Build .Net

on:
   workflow_dispatch:
   pull_request:
    branches: [ master ]

jobs:    
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    
    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test
      